### PR TITLE
Added as_of parameter to get_option_contracts

### PR DESCRIPTION
**Pull request by vitteloil**
https://polygon.io/docs/options/get_v3_reference_options_contracts supports an as_of parameter.

### CODE REVIEW

**Comment by pssolanki111** [comment]
Hey, Thank you so much for the contribution @vitteloil 

Just to confirm, you have tested this change with an actual API call? also when was this added.

(PS consider joining our discord server if you prefer to use that for comms)

**Comment by vitteloil** [comment]
Hello,
Yep I'm using this PR myself. The REST api version. I didn't test the async one but my guess is it should work the same ?
Not sure when this was added : I am using polygon's API since.. this morning only.

**Comment by pssolanki111** [comment]
Yes. Logically it should. and great to know it works on sync client

If you could go ahead and just make one test request on the async version, it would be great (it's the same thing just with async-awaits)

I'm unable to test just yet cause I recently started a new role so low on bandwidth at this moment.

**Comment by pssolanki111** [comment]
Great work @vitteloil 

Thanks for the contribution.

**Pull request merged**
